#! /bin/bash
if [ -z "$(WINDOW_ID=$(xdotool search --onlyvisible --class zotero); echo $WINDOW_ID)" ] && [ -z "$(pidof kdocker)" ]; then
    zotero &
    WINDOW_ID=$(printf 0x%x $(xdotool search --onlyvisible --sync  --class zotero)) # WINDOW_ID in hex
    kdocker -w $WINDOW_ID -q &
else
    if [ -z "$(WINDOW_ID=$(xdotool search --onlyvisible --class zotero); echo $WINDOW_ID)" ]; then 
        zotero &
    else 
        xdotool search --onlyvisible --sync --class zotero windowminimize
    fi    
fi
