#! /bin/bash

# zotero-tray 
# 
# Copyright (C) 2018  Alexandru-Catalin Petrini (alexandru.c.petrini@gmail.com)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.

# This program is distributed in the hope that it will be useful,# # # 
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.



CLASS=zotero
PROGRAM=zotero
MAIN_EXEC=zotero-bin
if [ -z "$(WINDOW_ID=$(xdotool search --onlyvisible --class $CLASS); echo $WINDOW_ID)" ] && [ -z "$(pidof $MAIN_EXEC)" ]; then
    $PROGRAM &
    WINDOW_ID=$(printf 0x%x $(xdotool search --onlyvisible --sync  --class $CLASS)) # WINDOW_ID in hex
    kdocker -w $WINDOW_ID -q &
else
    WINDOW_ID=$(xdotool search --onlyvisible --class $CLASS)
    if [ -z "$WINDOW_ID" ]; then 
        $PROGRAM &
    else 
        xdotool windowminimize --sync  $WINDOW_ID
    fi    
fi
